apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: consul-proxy
  labels:
    name: consul-proxy
spec:
  selector:
    matchLabels:
      name: consul-proxy
  template:
    metadata:
      labels:
        name: consul-proxy
    spec:
      containers:
      - name: proxy-to-service
        image: gcr.io/google_containers/proxy-to-service:v2
        args: [ "tcp", "8500", "consul.default" ]
        ports:
        - name: http
          protocol: TCP
          containerPort: 8500
          hostPort: 8500
